Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"

  config.vm.provider "libvirt" do |lv|
    lv.default_prefix = ""
  end

  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    apt-get install -y curl
  SHELL

  config.vm.define "yel-boukS" do |server|
    server.vm.hostname = "yel-boukS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "libvirt" do |vb|
      vb.memory = 1536
      vb.cpus = 1
      vb.machine_type = "pc"
      vb.driver = "qemu"
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

end