Vagrant.configure("2") do |config|

  config.vm.box = "debian/bookworm64"
  
  config.vm.provider "libvirt" do |lv|
    lv.default_prefix = ""
  end

  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get upgrade -y
    apt-get install -y curl
    if [ ! -f /swapfile ]; then
      fallocate -l 1G /swapfile
      chmod 600 /swapfile
      mkswap /swapfile
      swapon /swapfile
      echo '/swapfile none swap sw 0 0' >> /etc/fstab
    fi
  SHELL

  config.vm.define "yel-boukS" do |server|
    server.vm.hostname = "yel-boukS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "libvirt" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.machine_type = "pc"
      vb.driver = "qemu"
    end
    server.vm.provision "shell", path: "scripts/server.sh"
  end

  config.vm.define "yel-boukSW" do |agent|
    agent.vm.hostname = "yel-boukSW"
    agent.vm.network "private_network", ip: "192.168.56.111"
    agent.vm.provider "libvirt" do |vb|
      vb.memory = 1024
      vb.cpus = 1
      vb.machine_type = "pc"
      vb.driver = "qemu"
    end
    agent.vm.provision "shell", path: "scripts/agent.sh"
  end

end